### ISSUE TITLE
Creation of spot price triggered orders fails due to go marshalling

### ISSUE THREAD

**Issue by Lukazoid** [gateio/gateapi-csharp#15]
Using `SpotApi.CreateSpotPriceTriggeredOrderAsync`:

```csharp
var spotPriceTriggeredOrder = new SpotPriceTriggeredOrder(new SpotPriceTrigger(
        gateIoTradeValues.PriceString,
        triggerRule,
        _optionsMonitor.CurrentValue.TriggeredOrderExpirationSeconds),
    new SpotPricePutOrder(side: SpotPricePutOrder.SideEnum.Sell,
        amount: gateIoTradeValues.AmountString,
        price: gateIoTradeValues.PriceString,
        account: SpotPricePutOrder.AccountEnum.Normal),
    ToCurrencyPairString(buyOrder.ExchangeRate.AssetTokenPair));
await spotApi.CreateSpotPriceTriggeredOrderAsync(spotPriceTriggeredOrder)
    .ConfigureAwait(false);
```
`spotPriceTriggeredOrder.ToJson()` looks like the following:

```json
{
  "trigger": {
    "rule": "<=",
    "price": "0.236640",
    "expiration": 604800
  },
  "put": {
    "side": "sell",
    "account": "normal",
    "time_in_force": null,
    "type": "limit",
    "price": "0.236640",
    "amount": "6.85"
  },
  "id": 0,
  "user": 0,
  "market": "DOGE_USDT",
  "ctime": 0.0,
  "ftime": 0.0,
  "fired_order_id": 0,
  "status": null,
  "reason": null
}
```

Looks like your Go backend isn't expecting to receive floats for ctime:

```
Io.Gate.GateApi.Client.GateApiException: {"message":"invalid json json: cannot unmarshal number 0.0 into Go struct field TouchOrderV4.ctime of type int64","label":"INVALID_REQUEST_BODY"}
   at Io.Gate.GateApi.Api.SpotApi.CreateSpotPriceTriggeredOrderAsyncWithHttpInfo(SpotPriceTriggeredOrder spotPriceTriggeredOrder)
   at Io.Gate.GateApi.Api.SpotApi.CreateSpotPriceTriggeredOrderAsync(SpotPriceTriggeredOrder spotPriceTriggeredOrder)
```

**Comment by revilwang** [comment]
Thanks for reporting the issue. I'll remove the read-only items from request body to avoid this problem.

**Comment by revilwang** [comment]
Which version are you using specifically?

**Comment by revilwang** [comment]
New version 4.22.4 has been uploaded to NuGet and should be available to download shortly. The data type has been changed to long and such read-only fields will not be sent to server any more.

**Comment by Lukazoid** [comment]
I was using 4.22.3. I'll verify the updated version works later today and close then. Thanks a lot 👍

**Comment by Lukazoid** [comment]
That has worked excellently, thanks once again
