### ISSUE TITLE
CurrencyPair always null

### ISSUE THREAD

**Issue by Printscan** [gateio/gateapi-csharp#36]
if (string.IsNullOrEmpty(currencyPair))
{
     continue;
}
     Console.WriteLine(currencyPair);

try
{
    var order = new Order
    {
        CurrencyPair = currencyPair,
        Amount = orderBids[0],
        Price = orderBids[1],
        Side = Order.SideEnum.Sell,
        Type = Order.TypeEnum.Limit, // Предполагается, что это лимитный ордер
        Iceberg = "0",
        TimeInForce = Order.TimeInForceEnum.Gtc,
        AutoBorrow = false,
        StpAct = Order.StpActEnum.Cn
    };

    result.Add(await _spotApi.CreateOrderAsync(order));
}
catch (Exception ex)
{
    Console.WriteLine("Произошло исключение: " + ex.Message);
    Console.WriteLine("StackTrace: " + ex.StackTrace);

    if (ex.InnerException != null)
    {
        Console.WriteLine("Внутреннее исключение: " + ex.InnerException.Message);
        Console.WriteLine("StackTrace внутреннего исключения: " + ex.InnerException.StackTrace);
    }
}
 System.InvalidOperationException
  HResult=0x80131509
  Сообщение = currencyPair is a required property for Order and cannot be null (Parameter 'currencyPair')
  Источник = ConsoleApp2
  Трассировка стека:
   в GateIoApiClient.<SellAllOfCurrenciesAsync>d__7.MoveNext() в D:\Работа\ConsoleApp2\ConsoleApp2\Program.cs:строка 88
   в MyApp.Program.<Main>d__0.MoveNext() в D:\Работа\ConsoleApp2\ConsoleApp2\Program.cs:строка 102
   

currency Pair всегда null даже после проверки на null, в чем причина?

**Comment by 0x5487** [comment]
Have you passed 'currencyPair' parameter 

```c#
var order = new Order
{
CurrencyPair = currencyPair, // what is the value of currencyPair?
};
```

**Comment by Printscan** [comment]
IRON_USDT
Произошло исключение: currencyPair is a required property for Order and cannot be null (Parameter 'currencyPair')
StackTrace:    at Io.Gate.GateApi.Model.Order..ctor(String text, String currencyPair, Nullable`1 type, String account, SideEnum side, String amount, String price, Nullable`1 timeInForce, String iceberg, Boolean autoBorrow, Boolean autoRepay, Nullable`1 stpAct)
   at GateIoApiClient.SellAllOfCurrenciesAsync() in D:\Работа\ConsoleApp2\ConsoleApp2\Program.cs:line 83
--------------------------------------------------------------------------------------------------------------------------------------------
if (string.IsNullOrEmpty(currencyPair))
    continue;

Console.WriteLine(currencyPair);
try
{
    var order = new Order
    {
        CurrencyPair = currencyPair,
        Amount = orderBids[0],
        Price = orderBids[1],
        Side = Order.SideEnum.Sell,
        Type = Order.TypeEnum.Limit,
        Iceberg = "0",
        TimeInForce = Order.TimeInForceEnum.Gtc,
        AutoBorrow = false,
        StpAct = Order.StpActEnum.Cn
    };

    result.Add(await _spotApi.CreateOrderAsync(order));
}
catch (Exception ex)
{
    Console.WriteLine("Произошло исключение: " + ex.Message);
    Console.WriteLine("StackTrace: " + ex.StackTrace);

    if (ex.InnerException != null)
    {
        Console.WriteLine("Внутреннее исключение: " + ex.InnerException.Message);
        Console.WriteLine("StackTrace внутреннего исключения: " + ex.InnerException.StackTrace);
    }
}
--------------------------------------------------------------------------------------------------------------------------------------------
    I'm sure that the data is correct
